# See config.example.yml for documentation.
object_base: orig/GSAP01
object: sys/main.dol
hash: c1a6ccdc61c7e719e20ea7cc59c8de09fd183e66
symbols: config/GSAP01/symbols.txt
splits: config/GSAP01/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
