# See config.example.yml for documentation.
object_base: orig/GSAE01
object: sys/main.dol
hash: 8bde4669c75260cc058b8b44ef36bacff3a67d20
symbols: config/GSAE01/symbols.txt
splits: config/GSAE01/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
